services:
  - type: web
    name: pjsofonic-erp-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://pjsofonic-erp-backend.onrender.com/api
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://ffauweryjzpnskdaqcyp.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_bLkboY3aqcA-LRqg7VROgw_IjxTh84f
      - key: NEXT_PUBLIC_EMS_API_BASE
        value: https://erp-backend-1-02lc.onrender.com/api
      - key: NEXT_PUBLIC_CRM_API_BASE
        value: https://pjsofonic-crm-backend.onrender.com
      - key: NEXT_PUBLIC_PROJECTOS_API_BASE
        value: https://sofo-projectos.onrender.com
      - key: NEXT_PUBLIC_QMS_API_BASE
        value: https://pjsofonic-qms.onrender.com
