services:
  - type: web
    name: pjsofonic-erp-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://pjsofonic-erp-backend.onrender.com/api
